"use client";
import React from "react";
// import { makeStyles } from "@material-ui/core/styles";
import { makeStyles } from "@mui/material/styles";

import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import Divider from "@mui/material/Divider";
import ListItemText from "@mui/material/ListItemText";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import Avatar from "@mui/material/Avatar";
import Typography from "@mui/material/Typography";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};
const page = () => {
  const styles = {
    backgroundImage: 'url("about.webp")',
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    minHeight: "690px",
    // Additional styles
  };
  return (
    <>
      <div style={styles}>
        <div className="container">
          <h1
            style={{ color: "white", margin: "0px auto", maxWidth: "1100px" }}
          >
            About
          </h1>
          <div
            style={{
              margin: "0px auto",
              maxWidth: "1100px",
              backgroundColor: "white",
              padding: "20px",
            }}
          >
            As a 3-year experienced web developer, I have a solid understanding
            of web development technologies and best practices, as well as
            hands-on experience in building and maintaining web applications. I
            am proficient in front-end and back-end technologies such as HTML,
            CSS, JavaScript, and WordPress, as well as libraries like React JS.
            I am also skilled in back-end technologies such as PHP and have
            experience working with databases like MySQL. My expertise includes
            designing responsive and user-friendly interfaces, optimizing
            website performance, and implementing security measures to protect
            sensitive data. Additionally, I have experience collaborating with
            cross-functional teams, including designers and project managers, to
            deliver high-quality products on time and within budget. I am always
            eager to learn and stay up-to-date with the latest trends and
            technologies in web development. I am committed to writing clean and
            maintainable code that is scalable and reusable, and I strive to
            create engaging user experiences that exceed expectations. Overall,
            I am a dedicated and results-driven web developer with a passion for
            creating innovative solutions to complex problems.
            <List>
              <ListItem alignItems="flex-start">
                <ListItemAvatar>
                  <Avatar alt="Remy Sharp" src="/Fanshawe_College.png" />
                </ListItemAvatar>
                <ListItemText
                  primary="Fanshawe College"
                  secondary={
                    <React.Fragment>
                      <Typography
                        component="span"
                        variant="body2"
                        color="textPrimary"
                      >
                        Software and Information Systems Testing (Co-op)
                      </Typography>
                      {
                        " — Skills: Object-Oriented Programming (OOP) · Testing · Test Automation · Manual Testing · Core Java · Java"
                      }
                    </React.Fragment>
                  }
                />
              </ListItem>
              <Divider variant="inset" component="li" />
              <ListItem alignItems="flex-start">
                <ListItemAvatar>
                  <Avatar alt="Travis Howard" src="/pcte.webp" />
                </ListItemAvatar>
                <ListItemText
                  primary="PCTE Group of Institutes – Ludhiana, Punjab – India"
                  secondary={
                    <React.Fragment>
                      <Typography
                        component="span"
                        variant="body2"
                        // className={classes.inline}
                        color="textPrimary"
                      >
                        Masters of Computer Applications
                      </Typography>
                      {" — Wish I could come, but I'm out of town this…"}
                    </React.Fragment>
                  }
                />
              </ListItem>
              <Divider variant="inset" component="li" />
              <ListItem alignItems="flex-start">
                <ListItemAvatar>
                  <Avatar alt="Cindy Baker" src="/ggn.png" />
                </ListItemAvatar>
                <ListItemText
                  primary="GUJRANWALA GURU NANAK KHALSA COLLEGE – Ludhiana, Punjab
                  – India"
                  secondary={
                    <React.Fragment>
                      <Typography
                        component="span"
                        variant="body2"
                        // className={classes.inline}
                        color="textPrimary"
                      >
                        Bachelor of Computer Science
                      </Typography>
                      {" — Do you have Paris recommendations? Have you ever…"}
                    </React.Fragment>
                  }
                />
              </ListItem>
            </List>
          </div>
        </div>
      </div>
    </>
  );
};

export default page;
